config/routes.rb
Rails.application.routes.draw do

  # root to: 'application#angular'
  root to: "pages#home"

  #users
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { registrations: "registrations"}
  match '/users/:id', :to => 'users#show', :as => :user,  :via => :get #display specific user show page

  #foods
  resources :foods do
    collection do
      get :autocomplete
    end
  end

  resources :foods do
    resources :reviews, only: [:create]
  end

  resources :categories
  resources :locations

  get 'dashboard', to: "pages#dashboard"

  devise_scope :user do
    authenticated :user do
      root 'pages#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  has_many :food_categories
  has_many :foods, through: :food_categories

  mount_uploader :photo, PhotoUploader
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :update, :edit, :destroy]
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to category_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :photo)
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for @category, :html => {:class=> 'form-signin'} do |f| %>
<%= f.error_notification %>
<h3 class='text-center'>Add Category</h3>
  <%= f.input :name, required: true, autofocus: true, label: false, placeholder: "name", input_html: {class: "form-control"} %>
   <%= f.file_field :photo %>
  <%= f.button :submit, class:'btn btn-success btn-lg btn-block' %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="text-center">Categories</h3>
      <% if user_signed_in? and current_user.admin? %>
        <h6><%= link_to "Add Category", new_category_path %></h6>
        <h6><%= link_to "Add Location", locations_path %></h6>
      <% end %>
      <br>
      <br>
      <% @categories.each do |category| %>
        <div class="col-md-4">
          <center><%= link_to (image_tag category.photo_url(:thumb).to_s), category %></center>
          <h4 class="text-center"><%= link_to category.name, category %></h4>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <h3><%= @category.name %></h3>
    <% if user_signed_in? and current_user.admin? %>
      <h4><%= link_to "Edit", edit_category_path %> || <%= link_to "Delete", category_path, method: :delete %></h4>
    <% end %>
    <br>
    <% @category.foods.each do |food| %>
      <div class="col-md-3">
        <center><%= link_to (image_tag food.image_url(:thumb).to_s), food %></center>
        <h3 class="text-center"><%= food.name %></h3>
      </div>
    <% end %>
  </div>
</div>