config/routes.rb
Rails.application.routes.draw do

  # root to: 'application#angular'
  root to: "pages#home"

  #users
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { registrations: "registrations"}
  match '/users/:id', :to => 'users#show', :as => :user,  :via => :get #display specific user show page

  #foods
  resources :foods do
    collection do
      get :autocomplete
    end
  end

  resources :foods do
    resources :reviews, only: [:create]
  end

  resources :categories
  resources :locations

  get 'dashboard', to: "pages#dashboard"

  devise_scope :user do
    authenticated :user do
      root 'pages#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to "hati", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div id="container">
        <%= form_tag locations_path, method: "get", class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "type a location" %>
        </div>
        <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li><%= link_to "#{current_user.username}", dashboard_path %></li>
          <li><%= link_to "Inbox", mailbox_inbox_path %></li>
           <li><%= link_to "Products", categories_path %></li>
           <li><%= link_to "Locations", locations_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Cultivi</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'>
  <link href="/stylesheets/one-page-wonder.css.scss" rel="stylesheet">
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js" %>
  <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <% flash.each do |key, value| %>
    <div class="flash">
      <div class="alert text-center <%= flash_class(key) %>">
        <button class="close" data-dismiss="alert">X</button>
        <%= value %>
      </div>
    </div>
  <% end %>
  <div class="container">
  <%= yield %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</body>
</html>